using System;
using System.Collections.Generic;

namespace SmartMacro.Api.Models;

public partial class MealLog
{
    public long LogId { get; set; }

    public long UserId { get; set; }

    public long FoodId { get; set; }

    public long? InventoryId { get; set; }

    public DateOnly LogDate { get; set; }

    public string MealSlot { get; set; } = null!;

    public decimal ConsumedGrams { get; set; }

    public decimal KcalSnapshot { get; set; }

    public decimal ProteinGSnapshot { get; set; }

    public decimal CarbsGSnapshot { get; set; }

    public decimal FatGSnapshot { get; set; }

    public bool IsAutoGenerated { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Food Food { get; set; } = null!;

    public virtual UserFoodInventory? Inventory { get; set; }

    public virtual User User { get; set; } = null!;
}
