// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMacro.Api.Models;

#nullable disable

namespace SmartMacro.Api.Migrations
{
    [DbContext(typeof(SmartMacroDbContext))]
    [Migration("20260811040544_HashRefreshTokens")]
    partial class HashRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMacro.Api.Models.ActivityLog", b =>
                {
                    b.Property<long>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("activity_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityLogId"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("activity_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("KcalBurned")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("kcal_burned");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ActivityLogId");

                    b.HasIndex(new[] { "UserId", "LogDate" }, "IX_activity_user_date");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.DailyTarget", b =>
                {
                    b.Property<long>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TargetId"));

                    b.Property<long?>("ComputedFromRuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("computed_from_rule_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("TargetCarbsG")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("target_carbs_g");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<decimal>("TargetFatG")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("target_fat_g");

                    b.Property<decimal>("TargetKcal")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("target_kcal");

                    b.Property<decimal>("TargetProteinG")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("target_protein_g");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TargetId");

                    b.HasIndex("ComputedFromRuleId");

                    b.HasIndex(new[] { "UserId", "TargetDate" }, "UQ_target_user_date")
                        .IsUnique();

                    b.ToTable("daily_targets", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.Food", b =>
                {
                    b.Property<long>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FoodId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("barcode");

                    b.Property<decimal>("CarbsGPer100g")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("carbs_g_per_100g");

                    b.Property<short?>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<decimal>("FatGPer100g")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("fat_g_per_100g");

                    b.Property<decimal?>("FiberGPer100g")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("fiber_g_per_100g");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("food_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<decimal>("KcalPer100g")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("kcal_per_100g");

                    b.Property<decimal>("ProteinGPer100g")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("protein_g_per_100g");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("user_submitted")
                        .HasColumnName("source");

                    b.HasKey("FoodId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "KcalPer100g", "ProteinGPer100g", "CarbsGPer100g", "FatGPer100g" }, "IX_foods_macro");

                    b.HasIndex(new[] { "Barcode" }, "UQ_foods_barcode")
                        .IsUnique()
                        .HasFilter("([barcode] IS NOT NULL)");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.FoodCategory", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.HasIndex(new[] { "CategoryName" }, "UQ_food_categories_name")
                        .IsUnique();

                    b.ToTable("food_categories", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.MacroAdjustmentRule", b =>
                {
                    b.Property<long>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RuleId"));

                    b.Property<decimal>("CarbRatio")
                        .HasColumnType("decimal(4, 3)")
                        .HasColumnName("carb_ratio");

                    b.Property<short>("CycleTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("cycle_type_id");

                    b.Property<decimal>("FatRatio")
                        .HasColumnType("decimal(4, 3)")
                        .HasColumnName("fat_ratio");

                    b.Property<decimal>("KcalMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 3)")
                        .HasDefaultValue(1.000m)
                        .HasColumnName("kcal_multiplier");

                    b.Property<decimal>("ProteinGPerKgBw")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("protein_g_per_kg_bw");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RuleId");

                    b.HasIndex("CycleTypeId");

                    b.HasIndex(new[] { "UserId", "CycleTypeId" }, "UQ_rules_user_cycletype")
                        .IsUnique();

                    b.ToTable("macro_adjustment_rules", null, t =>
                        {
                            t.HasTrigger("TRG_rules_after_delete_nullify_targets");

                            t.HasTrigger("TRG_rules_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.MealLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<decimal>("CarbsGSnapshot")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("carbs_g_snapshot");

                    b.Property<decimal>("ConsumedGrams")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("consumed_grams");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("FatGSnapshot")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("fat_g_snapshot");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<long?>("InventoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    b.Property<bool>("IsAutoGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_auto_generated");

                    b.Property<decimal>("KcalSnapshot")
                        .HasColumnType("decimal(7, 2)")
                        .HasColumnName("kcal_snapshot");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("meal_slot");

                    b.Property<decimal>("ProteinGSnapshot")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("protein_g_snapshot");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("FoodId");

                    b.HasIndex("InventoryId");

                    b.HasIndex(new[] { "UserId", "LogDate" }, "IX_meallog_user_date");

                    b.ToTable("meal_logs", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TokenHash" }, "UQ_refresh_tokens_token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.TrainingCycleType", b =>
                {
                    b.Property<short>("CycleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cycle_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CycleTypeId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type_code");

                    b.HasKey("CycleTypeId");

                    b.HasIndex(new[] { "TypeCode" }, "UQ_training_cycle_types_code")
                        .IsUnique();

                    b.ToTable("training_cycle_types", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("moderate")
                        .HasColumnName("activity_level");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("goal_type");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("char(60)")
                        .HasColumnName("password_hash")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_users_email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasTrigger("TRG_users_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserBodyMetric", b =>
                {
                    b.Property<long>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MetricId"));

                    b.Property<decimal?>("BmrKcal")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("bmr_kcal");

                    b.Property<decimal?>("BodyFatPercent")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("body_fat_percent");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("height_cm");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date")
                        .HasColumnName("recorded_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("MetricId");

                    b.HasIndex(new[] { "UserId", "RecordedDate" }, "IX_metrics_user_date_desc")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId", "RecordedDate" }, "UQ_metrics_user_date")
                        .IsUnique();

                    b.ToTable("user_body_metrics", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserFoodInventory", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryId"));

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint")
                        .HasColumnName("food_id");

                    b.Property<decimal>("QuantityGrams")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("quantity_grams");

                    b.Property<string>("UnitNote")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit_note");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("InventoryId");

                    b.HasIndex("FoodId");

                    b.HasIndex(new[] { "UserId", "ExpiryDate" }, "IX_inventory_user_expiry");

                    b.HasIndex(new[] { "UserId", "QuantityGrams" }, "IX_inventory_user_qty");

                    b.HasIndex(new[] { "UserId", "FoodId", "ExpiryDate" }, "UQ_inventory_user_food_expiry")
                        .IsUnique()
                        .HasFilter("[expiry_date] IS NOT NULL");

                    b.ToTable("user_food_inventory", null, t =>
                        {
                            t.HasTrigger("TRG_inventory_after_delete_nullify_meallogs");

                            t.HasTrigger("TRG_inventory_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserTrainingSchedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<short>("CycleTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("cycle_type_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date")
                        .HasColumnName("schedule_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CycleTypeId");

                    b.HasIndex(new[] { "UserId", "ScheduleDate" }, "UQ_schedule_user_date")
                        .IsUnique();

                    b.ToTable("user_training_schedule", (string)null);
                });

            modelBuilder.Entity("SmartMacro.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_activity_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.DailyTarget", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.MacroAdjustmentRule", "ComputedFromRule")
                        .WithMany("DailyTargets")
                        .HasForeignKey("ComputedFromRuleId")
                        .HasConstraintName("FK_target_rule");

                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("DailyTargets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_target_user");

                    b.Navigation("ComputedFromRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.Food", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.FoodCategory", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_foods_category");

                    b.HasOne("SmartMacro.Api.Models.User", "CreatedByNavigation")
                        .WithMany("Foods")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_foods_created_by");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.MacroAdjustmentRule", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.TrainingCycleType", "CycleType")
                        .WithMany("MacroAdjustmentRules")
                        .HasForeignKey("CycleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_rules_cycle_type");

                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("MacroAdjustmentRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rules_user");

                    b.Navigation("CycleType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.MealLog", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.Food", "Food")
                        .WithMany("MealLogs")
                        .HasForeignKey("FoodId")
                        .IsRequired()
                        .HasConstraintName("FK_meallog_food");

                    b.HasOne("SmartMacro.Api.Models.UserFoodInventory", "Inventory")
                        .WithMany("MealLogs")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("FK_meallog_inventory");

                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("MealLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_meallog_user");

                    b.Navigation("Food");

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_refresh_tokens_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserBodyMetric", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("UserBodyMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_metrics_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserFoodInventory", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.Food", "Food")
                        .WithMany("UserFoodInventories")
                        .HasForeignKey("FoodId")
                        .IsRequired()
                        .HasConstraintName("FK_inventory_food");

                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("UserFoodInventories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_inventory_user");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserTrainingSchedule", b =>
                {
                    b.HasOne("SmartMacro.Api.Models.TrainingCycleType", "CycleType")
                        .WithMany("UserTrainingSchedules")
                        .HasForeignKey("CycleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_schedule_cycle_type");

                    b.HasOne("SmartMacro.Api.Models.User", "User")
                        .WithMany("UserTrainingSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_schedule_user");

                    b.Navigation("CycleType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.Food", b =>
                {
                    b.Navigation("MealLogs");

                    b.Navigation("UserFoodInventories");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.MacroAdjustmentRule", b =>
                {
                    b.Navigation("DailyTargets");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.TrainingCycleType", b =>
                {
                    b.Navigation("MacroAdjustmentRules");

                    b.Navigation("UserTrainingSchedules");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("DailyTargets");

                    b.Navigation("Foods");

                    b.Navigation("MacroAdjustmentRules");

                    b.Navigation("MealLogs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserBodyMetrics");

                    b.Navigation("UserFoodInventories");

                    b.Navigation("UserTrainingSchedules");
                });

            modelBuilder.Entity("SmartMacro.Api.Models.UserFoodInventory", b =>
                {
                    b.Navigation("MealLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
